import { useCallback, useEffect, useState } from 'react';
import AuditLogDetailsModal from '../components/audit/AuditLogDetailsModal';
import EmptyState from '../components/common/EmptyState';
import ErrorState from '../components/common/ErrorState';
import LoadingState from '../components/common/LoadingState';
import SystemAlerts from '../components/dashboard/SystemAlerts';
import { getAuthTimeline, listAuditLogs } from '../services/auditService';

function formatDateTime(value) {
  if (!value) return '—';
  try {
    return new Date(value).toLocaleString();
  } catch {
    return '—';
  }
}

function statusBadge(log) {
  const failed = log.status === 'failed' || log.action === 'LOGIN_FAILED';
  if (failed) return <span className="status-pill status-pill--failed">Failed</span>;
  if (log.status === 'success' || ['LOGIN_SUCCESS', 'LOGOUT', 'PASSWORD_CHANGED', 'LOGIN'].includes(log.action)) {
    return <span className="status-pill status-pill--success">Success</span>;
  }
  return <span className="status-pill">{log.status || '—'}</span>;
}

const AUTH_ACTIONS = [
  '',
  'LOGIN_SUCCESS',
  'LOGIN_FAILED',
  'LOGOUT',
  'PASSWORD_CHANGED',
  'PASSWORD_CHANGE_REQUIRED',
  'CREATE',
  'UPDATE',
  'ACTIVATE',
  'DEACTIVATE',
  'DELETE',
];

export default function AuditLogsPage() {
  const [logs, setLogs] = useState([]);
  const [pagination, setPagination] = useState({ page: 1, limit: 20, total: 0, pages: 1 });
  const [timeline, setTimeline] = useState([]);
  const [search, setSearch] = useState('');
  const [action, setAction] = useState('');
  const [status, setStatus] = useState('');
  const [role, setRole] = useState('');
  const [recordType, setRecordType] = useState('');
  const [accessSource, setAccessSource] = useState('');
  const [range, setRange] = useState('');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedLog, setSelectedLog] = useState(null);
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [authOnly, setAuthOnly] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const filters = {
        search,
        action,
        status,
        role,
        recordType,
        accessSource,
        range,
        from,
        to,
        page,
        limit: 20,
        sortField: 'createdAt',
        sortDir: 'desc',
        category: authOnly ? 'auth' : '',
      };
      const [result, events] = await Promise.all([
        listAuditLogs(filters),
        getAuthTimeline({ range, from, to, limit: 12 }),
      ]);
      setLogs(result.logs);
      setPagination(result.pagination);
      setTimeline(events);
    } catch (err) {
      setError(err.message || 'Unable to load audit logs.');
    } finally {
      setLoading(false);
    }
  }, [accessSource, action, authOnly, from, page, range, recordType, role, search, status, to]);

  useEffect(() => {
    const timer = setTimeout(load, 250);
    return () => clearTimeout(timer);
  }, [load]);

  useEffect(() => {
    setPage(1);
  }, [search, action, status, role, recordType, accessSource, range, from, to, authOnly]);

  const openDetails = (log) => {
    setSelectedLog(log);
    setDetailsOpen(true);
  };

  const start = pagination.total ? (pagination.page - 1) * pagination.limit + 1 : 0;
  const end = Math.min(pagination.page * pagination.limit, pagination.total);

  return (
    <div className="page-stack">
      <SystemAlerts loadFromApi compact={false} />

      <section className="panel">
        <div className="panel__header panel__header--spread">
          <div>
            <h2>Audit Logs</h2>
            <p className="muted">Permanent accountability records generated by the Backend.</p>
          </div>
          <label className="checkbox-inline">
            <input
              type="checkbox"
              checked={authOnly}
              onChange={(event) => setAuthOnly(event.target.checked)}
            />
            Login activity only
          </label>
        </div>

        <div className="toolbar toolbar--filters">
          <input
            className="toolbar__search"
            type="search"
            placeholder="Search user, email, action, IP…"
            value={search}
            onChange={(event) => setSearch(event.target.value)}
          />
          <select value={action} onChange={(event) => setAction(event.target.value)}>
            {AUTH_ACTIONS.map((item) => (
              <option key={item || 'all'} value={item}>
                {item || 'All actions'}
              </option>
            ))}
          </select>
          <select value={status} onChange={(event) => setStatus(event.target.value)}>
            <option value="">All statuses</option>
            <option value="success">Success</option>
            <option value="failed">Failed</option>
            <option value="info">Info</option>
          </select>
          <select value={role} onChange={(event) => setRole(event.target.value)}>
            <option value="">All roles</option>
            <option value="admin">Admin</option>
            <option value="police">Police</option>
          </select>
          <select value={accessSource} onChange={(event) => setAccessSource(event.target.value)}>
            <option value="">All sources</option>
            <option value="Admin Web">Admin Web</option>
            <option value="Police Web">Police Web</option>
            <option value="Web">Web</option>
            <option value="Citizen Mobile App">Citizen Mobile App</option>
          </select>
          <select value={range} onChange={(event) => setRange(event.target.value)}>
            <option value="">All time</option>
            <option value="today">Today</option>
            <option value="yesterday">Yesterday</option>
            <option value="last_7_days">Last 7 Days</option>
            <option value="last_30_days">Last 30 Days</option>
          </select>
          <input type="date" value={from} onChange={(event) => setFrom(event.target.value)} />
          <input type="date" value={to} onChange={(event) => setTo(event.target.value)} />
        </div>

        {timeline.length ? (
          <div className="audit-timeline">
            <h3>Security Event Timeline</h3>
            <ul>
              {timeline.map((event) => (
                <li key={event.id} className={`audit-timeline__item audit-timeline__item--${event.status || 'info'}`}>
                  <span className="audit-timeline__time">
                    {new Date(event.createdAt).toLocaleTimeString(undefined, {
                      hour: '2-digit',
                      minute: '2-digit',
                    })}
                  </span>
                  <div>
                    <strong>{event.action}</strong>
                    <p>
                      {event.actorName}
                      {event.actorRole ? ` • ${event.actorRole}` : ''}
                      {event.email && event.actorName === 'Unknown' ? ` • ${event.email}` : ''}
                    </p>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        ) : null}

        {loading ? <LoadingState message="Loading audit logs…" /> : null}
        {error ? <ErrorState message={error} onRetry={load} /> : null}

        {!loading && !error && !logs.length ? (
          <EmptyState
            title="No audit logs found"
            description="Authentication and admin actions will appear here automatically."
          />
        ) : null}

        {!loading && !error && logs.length ? (
          <>
            <div className="table-scroll">
              <table className="data-table data-table--compact audit-table">
                <thead>
                  <tr>
                    <th>Status</th>
                    <th>User</th>
                    <th>Role</th>
                    <th>Action</th>
                    <th>IP Address</th>
                    <th>Device</th>
                    <th>Browser</th>
                    <th>Source</th>
                    <th>Date/Time</th>
                    <th />
                  </tr>
                </thead>
                <tbody>
                  {logs.map((item) => (
                    <tr key={item.id}>
                      <td>{statusBadge(item)}</td>
                      <td className="cell-name">{item.actorName}</td>
                      <td className="cell-muted">{item.actorRole || '—'}</td>
                      <td>
                        <span className="type-chip">{item.action}</span>
                      </td>
                      <td className="cell-muted">{item.ipAddress || '—'}</td>
                      <td className="cell-muted">{item.device || '—'}</td>
                      <td className="cell-muted">{item.browser || '—'}</td>
                      <td className="cell-muted">{item.accessSource || '—'}</td>
                      <td className="cell-muted">{formatDateTime(item.createdAt)}</td>
                      <td>
                        <button type="button" className="btn btn--ghost btn--small" onClick={() => openDetails(item)}>
                          View
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="pagination-bar">
              <span>
                Showing {start}–{end} of {pagination.total} records
              </span>
              <div className="pagination-bar__actions">
                <button
                  type="button"
                  className="btn btn--ghost btn--small"
                  disabled={pagination.page <= 1}
                  onClick={() => setPage((value) => Math.max(1, value - 1))}
                >
                  Previous
                </button>
                <span>
                  Page {pagination.page} of {pagination.pages}
                </span>
                <button
                  type="button"
                  className="btn btn--ghost btn--small"
                  disabled={pagination.page >= pagination.pages}
                  onClick={() => setPage((value) => value + 1)}
                >
                  Next
                </button>
              </div>
            </div>
          </>
        ) : null}
      </section>

      <AuditLogDetailsModal
        open={detailsOpen}
        log={selectedLog}
        onClose={() => {
          setDetailsOpen(false);
          setSelectedLog(null);
        }}
      />
    </div>
  );
}
